### ISSUE TITLE
Idea: file and Folder structure should be restructured.

### ISSUE THREAD

**Issue by shaonkabir8** [AshuKulu/HactoberFest2020-Beginers#81]
🚀 Ideas:

Here's already a lot more of coolest things written in different language. And obviously It's quite hard enough to find out what are already in or not. 
So, If we organize our folder structure and maintenance our codes though README, It'd be perfect. 

Should I make a pull request updating my thinkings ? Hopefully that's gonna be awesome.

Thanks 😊

**Comment by Jonathanvanhaaften** [comment]
Ive sent a pull request

**Comment by AshuKulu** [comment]
Thank you
